SQL> select *
  2  from tab;

TNAME                          TABTYPE  CLUSTERID                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
------------------------------ ------- ----------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
BONUS                          TABLE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
CUSTOMERS                      TABLE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
DEPT                           TABLE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
EMP                            TABLE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
PRODUCTS                       TABLE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
SALGRADE                       TABLE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    

6 rows selected.

SQL> desc products
 Name                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Null?    Type
 ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- -------- ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 PID                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               NOT NULL NUMBER(2)
 PNAME                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             NOT NULL VARCHAR2(20)
 PRICE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             NOT NULL NUMBER(7,2)

SQL> insert into products values(
  2  1,"SANTOOR",100);
1,"SANTOOR",100)
  *
ERROR at line 2:
ORA-00984: column not allowed here 


SQL> insert into products values(
  2  01,"SANTOOR",100);
01,"SANTOOR",100)
   *
ERROR at line 2:
ORA-00984: column not allowed here 


SQL> insert into products values(
  2  01,'SANTOOR,100);
ERROR:
ORA-01756: quoted string not properly terminated 


SQL> insert into products values(
  2  01,'SANTOOR',100);

1 row created.

SQL> select *
  2  from products;

       PID PNAME                     PRICE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
---------- -------------------- ----------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         1 SANTOOR                     100                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              

SQL> insert into products values(
  2  (01,'SANTOOR,100),;
ERROR:
ORA-01756: quoted string not properly terminated 


SQL> insert into products values(
  2  (01,'SANTOOR,100),
  3  (02,'BABYJOHNSON',200),
  4  (03,'KARTHIKA',50));
ERROR:
ORA-01756: quoted string not properly terminated 


SQL> insert into products values(
  2  (01,'SANTOOR',100),
  3  (02,'BABYJOHNSON',200),
  4  (03,'KARTHIKA',50));
(01,'SANTOOR',100),
   *
ERROR at line 2:
ORA-00907: missing right parenthesis 


SQL> insert into products (pid,pname,price)values(
  2  (01,'SANTOOR',100),
  3  (02,'BABYJOHNSON',200),
  4  (03,'KARTHIKA',50));
(01,'SANTOOR',100),
   *
ERROR at line 2:
ORA-00907: missing right parenthesis 


SQL> insert into products (pid,pname,price)values
  2  (01,'SANTOOR',100),
  3  (02,'BABYJOHNSON',200),
  4  (03,'KARTHIKA',50);
(01,'SANTOOR',100),
                  *
ERROR at line 2:
ORA-00933: SQL command not properly ended 


SQL> insert all into products (pid,pname,price)values
  2  (01,'SANTOOR',100),
  3  (02,'BABYJOHNSON',200),
  4  (03,'KARTHIKA',50);
(01,'SANTOOR',100),
                  *
ERROR at line 2:
ORA-00928: missing SELECT keyword 


SQL> insert into products (pid,pname,price)values(
  2  (11,'SANTOOR',100),
  3  (21,'SANTOOR',100),
  4  (31,'SANTOOR',100));
(11,'SANTOOR',100),
   *
ERROR at line 2:
ORA-00907: missing right parenthesis 


SQL> insert into products  values(
  2  02,'BABYJOHNSON',200);

1 row created.

SQL> insert into products  values(
  2  03,'KARTHIKA',50);

1 row created.

SQL> insert into products  values(
  2  04,'BIKE',90000);

1 row created.

SQL> insert into products  values(
  2  04,'CAR',700000);
04,'CAR',700000)
         *
ERROR at line 2:
ORA-01438: value larger than specified precision allowed for this column 


SQL> insert into products  values(
  2  04,'CAR',950000);
04,'CAR',950000)
         *
ERROR at line 2:
ORA-01438: value larger than specified precision allowed for this column 


SQL> 04,'CAR',95000);
SP2-0734: unknown command beginning "04,'CAR',9..." - rest of line ignored.
SQL> insert into products  values(
  2  04,'CAR',95000);
insert into products  values(
*
ERROR at line 1:
ORA-00001: unique constraint (SCOTT.SYS_C0011683) violated 


SQL> insert into products  values(
  2  05,'CAR',95000);

1 row created.

SQL> select *
  2  from products;

       PID PNAME                     PRICE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
---------- -------------------- ----------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         1 SANTOOR                     100                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         2 BABYJOHNSON                 200                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         3 KARTHIKA                     50                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         4 BIKE                      90000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         5 CAR                       95000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              

SQL> update products
  2  set pname='CYCLE'
  3  where pid=4;

1 row updated.

SQL> select *
  2  from products;

       PID PNAME                     PRICE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
---------- -------------------- ----------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         1 SANTOOR                     100                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         2 BABYJOHNSON                 200                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         3 KARTHIKA                     50                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         4 CYCLE                     90000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         5 CAR                       95000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              

SQL> update products
  2  set pname='FOGG', price=300
  3  where pid=2;

1 row updated.

SQL> select *
  2  from products;

       PID PNAME                     PRICE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
---------- -------------------- ----------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         1 SANTOOR                     100                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         2 FOGG                        300                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         3 KARTHIKA                     50                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         4 CYCLE                     90000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         5 CAR                       95000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              

SQL> spool off
SQL> delete products
  2  where pname=1;
where pname=1
      *
ERROR at line 2:
ORA-01722: invalid number 


SQL> delete products
  2  where pid=1;

1 row deleted.

SQL> select *
  2  from products;

       PID PNAME                     PRICE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
---------- -------------------- ----------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         2 FOGG                        300                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         3 KARTHIKA                     50                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         4 CYCLE                     90000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         5 CAR                       95000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              

SQL> delete from products
  2  delete from products
  3  where pid=3;
delete from products
*
ERROR at line 2:
ORA-00933: SQL command not properly ended 


SQL> delete from products
  2  where pid=3;

1 row deleted.

SQL> select *
  2  from products;

       PID PNAME                     PRICE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
---------- -------------------- ----------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         2 FOGG                        300                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         4 CYCLE                     90000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         5 CAR                       95000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              

SQL> rollback;

Rollback complete.

SQL> select *
  2  from products;

no rows selected

SQL> rollback;

Rollback complete.

SQL> select *
  2  from products;

no rows selected

SQL> rollback;

Rollback complete.

SQL> select *
  2  from products;

no rows selected

SQL> insert into products  values(
  2  02,'BABYJOHNSON',200);

1 row created.

SQL> insert into products  values(
  2  01,'FOGG',300);

1 row created.

SQL> insert into products  values(
  2  05,'CAR',95000);

1 row created.

SQL> insert into products  values(
  2  04,'CYCLE',5000);

1 row created.

SQL> select *
  2  from products;

       PID PNAME                     PRICE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
---------- -------------------- ----------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         2 BABYJOHNSON                 200                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         1 FOGG                        300                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         5 CAR                       95000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         4 CYCLE                      5000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              

SQL> commit;

Commit complete.

SQL> select *
  2  from products;

       PID PNAME                     PRICE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
---------- -------------------- ----------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         2 BABYJOHNSON                 200                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         1 FOGG                        300                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         5 CAR                       95000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         4 CYCLE                      5000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              

SQL> rollback;

Rollback complete.

SQL> select *
  2  from products;

       PID PNAME                     PRICE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
---------- -------------------- ----------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         2 BABYJOHNSON                 200                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         1 FOGG                        300                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         5 CAR                       95000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         4 CYCLE                      5000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              

SQL> insert into products  values(
  2  03,'REFRIGERATOR',5000);

1 row created.

SQL> savepoint a;

Savepoint created.

SQL> insert into products  values(
  2  07,'WHEEL CHAIR',5000);

1 row created.

SQL> SAVEPOINT B;

Savepoint created.

SQL> insert into products  values(
  2  08,'BAG',1000);

1 row created.

SQL> SAVEPOINT C;

Savepoint created.

SQL> select *
  2  from products;

       PID PNAME                     PRICE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
---------- -------------------- ----------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         2 BABYJOHNSON                 200                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         1 FOGG                        300                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         5 CAR                       95000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         4 CYCLE                      5000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         3 REFRIGERATOR               5000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         7 WHEEL CHAIR                5000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         8 BAG                        1000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              

7 rows selected.

SQL> ROLLBACK TO B;

Rollback complete.

SQL> select *
  2  from products;

       PID PNAME                     PRICE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
---------- -------------------- ----------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         2 BABYJOHNSON                 200                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         1 FOGG                        300                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         5 CAR                       95000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         4 CYCLE                      5000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         3 REFRIGERATOR               5000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         7 WHEEL CHAIR                5000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              

6 rows selected.

SQL> insert into products  values(
  2  08,'BAG',1000);

1 row created.

SQL> SAVEPOINT B;

Savepoint created.

SQL> ROLLBACK TO A;

Rollback complete.

SQL> select *
  2  from products;

       PID PNAME                     PRICE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
---------- -------------------- ----------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         2 BABYJOHNSON                 200                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         1 FOGG                        300                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         5 CAR                       95000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         4 CYCLE                      5000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         3 REFRIGERATOR               5000 